openapi: 3.0.0

info:
  description: API used in Airport Project
  version: '1.0.0'
  contact:
    name: Airport Project
    url: https://airport.serguun42.ru
  license:
    name: 'BSL-1.0'
    url: 'https://github.com/serguun42/airport-frontend'
  title: Airport API
  x-logo:
    url: '/img/wide.png'

servers:
  - description: Airport Project Production, API v1
    url: https://airport.serguun42.ru/api/v1/
  - description: Airport Project Development, API v1
    url: https://airport.localhost/api/v1/

tags:
  - name: account
    description: 'Account actions: login, check permission, etc…'
  - name: entry
    description: 'Create, delete and modify flights'

paths:
  /account/check:
    get:
      description: Check account and permissions
      operationId: accountCheck
      tags:
        - account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                example:
                  success: true
        '401':
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '403':
          description: Forbidden. Low account permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '429':
          description: Too many requests
          content:
            text/plain:
              schema:
                type: string
                example: '429 Too Many Requests'
  /account/signin:
    post:
      description: Sign into exsisting account
      operationId: accountSignin
      tags:
        - account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  token:
                    type: string
                example:
                  success: true
                  token: abcdef
        '403':
          description: Passwords don't match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '406':
          description: Not acceptable payload (JSON-format usually)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '429':
          description: Too many requests
          content:
            text/plain:
              schema:
                type: string
                example: '429 Too Many Requests'
      requestBody:
        description: Logging payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPayload'      
  /account/signup:
    post:
      description: Sign into exsisting account
      operationId: accountSignup
      tags:
        - account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  token:
                    type: string
                example:
                  success: true
                  token: abcdef
        '403':
          description: Passwords don't match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '406':
          description: Not acceptable payload (JSON-format usually)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '409':
          description: Duplicating user. Change nickname
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '422':
          description: Too short nickname. Try larger
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        '429':
          description: Too many requests
          content:
            text/plain:
              schema:
                type: string
                example: '429 Too Many Requests'
      requestBody:
        description: Registering payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPayload'      
security:
  - tokenAuth: []
  - cookieAuth: []

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      name: X-Token
      in: header
      description: Used for in-app actions
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
      description: You can login to retrieve cookies on login-page

  schemas:
    APIError:
      type: object
      properties:
        error:
          type: boolean
          default: true
        code:
          type: number
        reason:
          type: string
      example:
        error: true
        code: 403
        reason: no_permission

    UserPayload:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
